### ISSUE TITLE
Quickstart parents should be renamed to plural Quickstarts

### ISSUE THREAD

**Issue by dhirajsb** [fabric8io/ipaas-quickstarts#722]
The parent projects should have plural names, i.e. `quickstarts`, `quickstarts-cdi`, etc., since it's confusing that `quickstart-cdi` isn't a single quickstart but a parent for multiple cdi *quickstarts*

**Comment by davsclaus** [comment]
yeah  you can say there is a little diffrence today in the folder names

- archetypes
- quickstart

though we like for the individual quickstarts to not have S in their artifact id, quickstart-camel-cdi, so I guess its correct as-is, and archetypes folder should be renamed to archetype

@rhuss any thought?

**Comment by rhuss** [comment]
the motivation about using a singular noun is that the project name can be directly infered from the directory structure, i.e. quickstart/cdi/camel -> quickstart-cdi-camel

I wonder whether we need the intermediate poms anyway. They only add to module bloat and don't provide any extra value (and only add unnecessarily to the build time). Since quickstarts are meant to be as self-contained as possible (for the cost of code duplication), there is really nothing to share for cdi, java, war, karaf in the intermediate poms. I would remove this level.

In such cases I typically include everything from the quickstart pom.xml, but this is probably a matter of taste.

**Comment by rhuss** [comment]
It's also consistent to have the parent project's artifact name being a part of the projects name itself (e.g. 'quickstart-cdi' is part of 'quickstart-cdi-camel-rest` (that's also why I'm not so a big fan of adding a '-parent' suffix to a parent pom). 

But well, that's again a convention for correlation stuff and hence obviously discussable.

**Comment by davsclaus** [comment]
lets keep the current structure, we have renamed a lot already
