### ISSUE TITLE
Java main class should be a property

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#828]
In the quickstarts that uses a java main class, we should put that as a property with a known key. This makes forge tooling easier, and also for users as they can spot the main class as a property. And today we duplicate the class in the d-m-p and hawt-app plugin

**Comment by jstrachan** [comment]
this kinda makes forge tooling much harder TBH - in terms of letting the user choose what value of main to use on a maven project; as the forge (devops-edit) command now needs to look around through all parent poms looking for the right <properties> to update for the right profiles the user is going to invoke so when you update the main via the forge wizard it writes to the correct place

**Comment by jstrachan** [comment]
I'd rather other plugins like hawt-app and fabric8 just pulls the value from the d-m-p plugin really - or we had some canonical place to put it (separate file maybe?)

**Comment by jimmidyson** [comment]
So should we revert the PR?

**Comment by davsclaus** [comment]
why is that different than before? We had 2-3 places the main class was repeated. Now its in the properties section where all the other options are listed.

I was actually in need of this when working on making fabric8-setup work

**Comment by davsclaus** [comment]
yes the forge tool is broken / outdated 
https://github.com/fabric8io/fabric8/issues/4951

**Comment by jstrachan** [comment]
so we need to be able to load and save the main class from any maven project at all- then save it again nicely without breaking it. 

A project may or may not use hawt-app (its not really a requirement for iPaaS really - plus folks might be using tomcat/jetty/wildfly/jboss for which hawt-app is of no use at all). A project now may or may not use maven properties.  That maven property could be defined in any pom.xml in any profile.

So now there's loads of permutations to deal with; do you read/write the d-m-p XML; do you find the right <properties> to read/write it - then what if there's a property and a non-property expression in the XML? What if hawt-app and d-m-p are configured differently?

Its a hot mess really. I'd rather just have 1 canonical place in the XML we look for really (or have a new file) - its hard enough getting tooling to work as it is without making it insanely complex just because for some reason we've decided to split the d-m-p into 2 mvn plugins for no real gain for an iPaaS developer who's using docker.

Life would be even simpler if we just had 1 maven plugin really ;)

**Comment by davsclaus** [comment]
Well maybe the forge tool should not care about hawt-app and just be d-m-p?

But from tooling pov its easier to find /properties/fabric8.mainClass than try to find it in d-m-p. The mainClass is also used in the exec-java plugin that allows the end user to run the project from mvn with 'mvn exec:java'. So it makes sense imho to define it once and use the placeholders in the d-m-p and exec:java. The d-m-p already uses a number of placeholders for image name and whatnot.

**Comment by jstrachan** [comment]
yeah - I was thinking for now lets just make the tooling only d-m-p aware.

**Comment by davsclaus** [comment]
works for me too, that makes the fabric8-setup simpler to maintain and get back on track.

**Comment by davsclaus** [comment]
lets keep it as-is so everyone is happy
